package com.csdn.design.patterns.thinking.specifications.refactoring.v4;

import com.csdn.design.patterns.thinking.specifications.refactoring.exception.IdGenerationFailureException;
import com.csdn.design.patterns.thinking.specifications.refactoring.v2.IdGenerator;
import com.csdn.design.patterns.thinking.specifications.refactoring.v2.LogTraceIdGenerator;
import com.google.common.annotations.VisibleForTesting;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Random;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.util.ObjectUtils;

/**
 * <p> 补充注释
 * <p> Id Generator that is used to generate random IDs.
 * <p> The IDs generated by this class are not absolutely unique,
 * <p> but the probability of duplication is very low.
 *
 * @Author: xiewenfeng
 * @Date: 2022/2/15 11:14
 */
public class RandomIdGenerator implements LogTraceIdGenerator {

  private static final Logger logger = LoggerFactory.getLogger(IdGenerator.class);

  /**
   * Generate the random ID. The IDs may be duplicated only in extreme situation.
   *
   * @return an random ID
   */
  @Override
  public String generate() {
    String substrOfHostName = getLastFieldOfHostName();
    long currentTimeMillis = System.currentTimeMillis();
    String randomString = generateRandomAlphameric(8);
    String id = String.format("%s-%d-%s", substrOfHostName, currentTimeMillis, randomString);
    return id;
  }

  /**
   * Get the local hostname and  extract the last field of the name string splitted by delimiter
   * '.'.
   *
   * @return the last field of hostname. Returns null if hostname is not obtained.
   */
  private String getLastFieldOfHostName() {
    String substrOfHostName = null;
    try {
      String hostName = InetAddress.getLocalHost().getHostName();
      if (ObjectUtils.isEmpty(hostName)) {
        logger.warn("hostName is null...");
        return null;
      }
      substrOfHostName = getLastSubstrSplittedByDot(hostName);
    } catch (UnknownHostException e) {
      logger.warn("Failed to get the host name.", e);
    }
    return substrOfHostName;
  }

  /**
   * Get the last field of {@hostName} splitted by delemiter '.'.
   *
   * @param hostName should not be null
   * @return the last field of {@hostName}. Returns empty string if {@hostName} is empty string.
   */
  @VisibleForTesting
  public String getLastSubstrSplittedByDot(String hostName) {
    if (ObjectUtils.isEmpty(hostName)) {
      return null;
    }
    String[] tokens = hostName.split("\\.");
    String substrOfHostName = tokens[tokens.length - 1];
    return substrOfHostName;
  }

  /**
   * Generate random string which only contains digits, uppercase letters and lowercase letters.
   *
   * @param length should not be less than 0
   * @return the random string. Returns empty string if {@length} is 0
   */
  @VisibleForTesting
  public String generateRandomAlphameric(int length) {
    if (length < 0) {
      return null;
    }
    char[] randomChars = new char[length];
    int count = 0;
    Random random = new Random();
    while (count < length) {
      int maxAscii = 'z';
      int randomAscii = random.nextInt(maxAscii);
      boolean isDigit = randomAscii >= '0' && randomAscii <= '9';
      boolean isUppercase = randomAscii >= 'A' && randomAscii <= 'Z';
      boolean isLowercase = randomAscii >= 'a' && randomAscii <= 'z';
      if (isDigit || isUppercase || isLowercase) {
        randomChars[count] = (char) (randomAscii);
        ++count;
      }
    }
    return new String(randomChars);
  }

  public static void main(String[] args) throws IdGenerationFailureException {
    IdGenerator idGenerator = new RandomIdGenerator();
    System.out.println(idGenerator.generate());
    System.out.println(idGenerator.generate());
  }
}
